language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
script:
  - make -C native clean all PLATFORM="$TRAVIS_OS_NAME" TARGET=jbit
  - make -C native clean all PLATFORM="$TRAVIS_OS_NAME" TARGET=io2sim
